# -*- coding: utf-8 -*-
"""calculator

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1612bDkZcXPBwK2LKQblE5yDhKJzLb0ji
"""

print("ARITHMETIC CALCULATOR")
print('''select operation
         Addition : +
      Subtraction : -
   Multiplication : *
         Division : /
        Remainder : %
           Square : ^''')
x=int(input("enter the number: "))
y=int(input("enter the number: "))
z=input("enter the operation(+,-,*,/,%,^) : ")

if z == "+":
  print(f"the addition of {x}+{y}={x+y}")

elif z == "-":
  print(f"the Subtraction of {x}-{y}={x-y}")

elif z == "*":
  print(f"the Multiplication of {x}*{y}={x*y}")

elif z == "/":
  print(f"the division of {x}/{y}={x/y}")

elif z == "%":
  print(f"the remainder of {x}%{y}={x%y}")

elif z == "^":
  print(f"the square of {x}^{y}={x**y}")

else:
  print("invalid operation")