# -*- coding: utf-8 -*-
"""password generator

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1jdGM6QQoRnlITl3KR9eT0EiDAXPXc_9B
"""

import random as ran
import string as sti

letters = sti.ascii_letters
digits = sti.digits
punctuation = sti.punctuation

password=""
print("--password generator--")
alphabets = int(input("number of letters in the password : "))
for i in range(1,alphabets+1):
  characters=ran.choice(letters)
  password+=characters

numbers = int(input("number of digits in the password : "))
for i in range(1,numbers+1):
  num=ran.choice(digits)
  password+=num

sp_characters = int(input("number of characters in the password : "))
for i in range(1,sp_characters+1):
  special_characters=ran.choice(punctuation)
  password+=special_characters

char_list = list(password)
ran.shuffle(char_list)
shuffled_string = ''.join(char_list)
print("the password is: {}".format(shuffled_string))