# -*- coding: utf-8 -*-
"""RPS_game

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1FoXXhTE_8y1ZTmURK_2gZMPZ3Br6tgHv
"""

import random

print("---:ROCK,PAPER,SCISSORS:--- ")


user_name=str(input("enter user name to start: "))
print("Hey {}! let's play Rock,paper and scissors ".format(user_name))
i = int(input("Enter target score: "))

computer_score=0
user_score=0


print('''---------------

1 :- ROCK
2 :- PAPER
3 :- SCISSORS
''')

while user_score < i  and computer_score < i:

  user=int(input('''---------------
enter choice: '''))



  if user < 1 or user > 3 :
     print("you lose invalid choice!")
     break

  else:
     computer=random.randint(1,3)
     print('computer choice is: {}'.format(computer))


     if computer==user:
       print("---it's a tie---")


     elif computer==1 and user==3:
       print("\n---computer win---")
       computer_score +=1
       print("\ncomputer score: {}".format(computer_score))
       print("{} score:{}".format(user_name,user_score))


     elif user==1 and computer==3:
       print("\n---{} win---".format(user_name))
       user_score+=1
       print("\n{} score:{}".format(user_name,user_score))
       print("computer score: {}".format(computer_score))

     elif computer > user:
       print("\n---computer win---")
       computer_score+=1
       print("\ncomputer score: {}".format(computer_score))
       print("{} score:{}".format(user_name,user_score))

     elif user > computer:
       print("\n---{} win---".format(user_name))
       user_score+=1
       print("\n{} score:{}".format(user_name,user_score))
       print("computer score: {}".format(computer_score))



if user_score == i :
  print("\n***{} Win's!*** ".format(user_name))
elif computer_score == i:
  print("\n***COMPUTER Win's***")
elif computer_score == user_score == i :
  print("***It's tie! play again*** ")